stages:
  - build-alpha
  - deploy-alpha

build-alpha:
  stage: build-alpha
  only:
    - alpha
  tags:
    - debian
    - dss
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t docker.ill.fr/webx/webx-relay:alpha --build-arg MAVEN_OPTS="$JAVA_OPTS" .
    - docker push docker.ill.fr/webx/webx-relay:alpha

deploy-alpha:
  stage: deploy-alpha
  only:
    - alpha
  tags:
    - debian
    - dss
  script:
    - ssh webx@webx-dev.ill.fr "cd /data/apps/webx-deploy; ./deploy.sh"
